# Generated by Django 5.1.4 on 2025-02-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='serial_number',
            field=models.CharField(blank=True, editable=False, max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='serial_number',
            field=models.CharField(blank=True, editable=False, max_length=14, unique=True),
        ),
    ]
