# Generated by Django 5.1.4 on 2025-03-01 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('passes', '0002_alter_card_serial_number_alter_ticket_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='accounts.userprofile'),
        ),
    ]
