# Generated by Django 5.1.4 on 2025-03-01 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0003_alter_card_owner_alter_ticket_owner'),
        ('validator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='qr_code',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='validator.qrcode'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='qr_code',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='validator.qrcode'),
        ),
    ]
