# Generated by Django 5.1.4 on 2025-03-01 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0004_card_qr_code_ticket_qr_code'),
        ('validator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='qr_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='validator.qrcode'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='qr_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='validator.qrcode'),
        ),
    ]
