# Generated by Django 5.1.4 on 2025-03-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='data',
            field=models.JSONField(default='no data'),
        ),
    ]
