# Generated by Django 5.1.4 on 2025-03-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0002_qrcode_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
