# Generated by Django 5.1.4 on 2025-03-09 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0003_alter_qrcode_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='data',
        ),
    ]
